a=input("d1:").split(",")
b=input("d2:").split(",")
c=input("d3:").split(",")
d=input("d4:").split(",")
a,c=sorted(a),sorted(c)
L=list(zip(a,b))
L1=dict(zip(c,d))
print("sd:",L)
L2=L.copy()
print("csd:",L2)
D=dict(zip(L,L1))

print("sk:",sorted(D.keys()))
print("sv:",sorted(D.values()))
print(D.update(D1))
